spring:
  application:
    name: code-gernator
  datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://10.17.149.182:3306/nsrm_cloud_biz_inquiry?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
       username: cdc_base_new
       password: 123456
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.16.87.99:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      routingTag: dev
      internalAnonPassword: ${spring.cloud.client.hostname}-${spring.cloud.client.ip-address}-${server.port}-${sysRandom:CsaWljuYd1}
ribbon:
  rule: local
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /