logging:
  level:
    root: info
    com.midea: debug
  file: logs/${spring.application.name}.log
  config: classpath:logback-prd.xml
  logstashhost: 10.0.3.184 #logstash服务器
spring:
  redis:
    host: 10.0.3.182
    port: 6379
    password: midea123456
    timeout: 60000
    jedis:
      pool:
        max-active: 100
        max-wait: 10
        max-Idle: 10
        min-Idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.3.172:3306/cloud_oauth?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: apprun
    password: sre5Prd!j4
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  eager-load:
    enabled: true
    clients: rbac-center
  ConnectTimeout: 5000
  ReadTimeout: 600000

## IDM系统设置
IDM:
  ## 是否使用Idm上的用户名/密码登陆(是-true,否false，生产的必须为true)
  userIdmPassword: true
  clientId: NSrm
  clientSecret: 696f4e32-e595-404d-8418-3a559318801e
  grantType: password
  ####code授权方式
  grantCodeType: authorization_code
  ####应用回调地址,需要http格式化（由于idm不支持#获取code，采用代理方式获取）
  redirectUrl: https://srm.longi-silicon.com:6080/sso
  ####通过用户名/密码获取Idm认证中心token
  accessTokenUrl: https://sso.longi-silicon.com:9050/esc-sso/oauth2.0/accessToken?client_id=%s&grant_type=%s&username=%s&password=%s
  ####获取IDM用户信息url
  profileUrl: https://sso.longi-silicon.com:9050/esc-sso/oauth2.0/profile?access_token=
  ####获取IDM认证中心校验是否有效
  checkAccessTokenUrl: https://sso.longi-silicon.com:9050/esc-sso/api/v1/loginLog/checkAccessToken?accesstoken=
  ####通过授权码获取Idm认证中心token
  accessTokenCodeUrl: https://sso.longi-silicon.com:9050/esc-sso/oauth2.0/accessToken?grant_type=%s&oauth_timestamp=%s&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
  ####IDM退出url
  logoutUrl: https://sso.longi-silicon.com:9050/esc-sso/logout
  ####检测自助服务是否正常，无宕机成功返回ok
  heartBeatUrl: https://sso.longi-silicon.com:9050/esc-self/heartbeat