logging:
  level:
    root: info
    com.midea: debug
  file: logs/${spring.application.name}.log
  config: classpath:logback-local.xml
  logstashhost: 10.0.10.50 #logstash服务器
spring:
  redis:
    host: 10.17.145.83
    port: 6379
    password: midea123456
    timeout: 60000
    jedis:
      pool:
        max-active: 100
        max-wait: 10
        max-Idle: 10
        min-Idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.17.149.182:3306/nsrm_cloud_biz_contract?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: cdc_base_new
    password: 123456
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  aop:
    proxy-target-class: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
mybatis-plus:
  type-aliases-package: com.midea.cloud.srm.model.contract
  mapper-locations: classpath*:/mybatis-mappers-extend/**/*.xml,classpath*:/mybatis-mappers-nextend/**/*.xml,classpath*:/mybatis-mappers/**/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml
security:
  oauth2:
    resource:
      prefer-token-info: false
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 600000
#elasticsearch
es:
  host: 10.17.145.110
  port: 9200
  scheme: http
template:
  contractTempId: 1751ac32ff05629370a37e44d9b88ba9
  contractSrmLink: http://10.16.87.99/#/formDataPreview?funName=contractManager&formId=$formId$
  acceptTempId: 1751aecac3c4d73be9421bf4e0fbf494
  acceptSrmLink: http://10.16.87.99/#/formDataPreview?funName=inspectionBill&formId=$formId$

CM_USER:
  cmUserName: longi_xansrm01
  cmPassword: 932f8f9cfa6d4bcd8fa8478f697cb227
  cmUrl: http://soatest.longi.com:8011/CMSSB/Esb/OeBlanket/ProxyServices/CmsSendOeBlanketSoapProxy?wsdl
ReceivableTypeInfo:
  RecUrl: http://10.0.10.26/fssc-eas-web/apis/ws/fssc/eas/thirdws/BusinessFormInfoServiceImpl?wsdl
  showAcceptOrderUrl: http://10.16.87.99/#/formDataPreview?funName=inspectionBill&formId=